services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ${DB_VOLUME}:${DB_VOLUME_PATH}
    networks:
      - ${DOCKER_NETWORK_NAME}

  app:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
    container_name: ${DOCKER_APP_CONTAINER_NAME}
    ports:
      - ${SPRING_APP_PORT}:${SPRING_APP_PORT}
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:${MYSQL_PORT}/${MYSQL_NAME}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - ${DOCKER_NETWORK_NAME}

volumes:
  order-data:

networks:
  delivery-system-network:
