name: Deploy to AWS EC2 using Docker

on:
  push:
    branches: ["main"]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name
  CONTAINER_NAME: your-container-name
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_SSH_USER: ec2-user
  PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
  TIMEZONE: Asia/Seoul
  HOST_PORT: 80
  CONTAINER_PORT: 8080
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  APPLICATION: ${{ secrets.APPLICATION }} # This should be a base64 encoded string of your application.properties

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    permissions: 
      contents: read

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up application.properties
      run: echo "${{ env.APPLICATION }}" > ./src/main/resources/application.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build JAR with Gradle
      run: ./gradlew build
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
    - name: Build Docker image
      run: docker build . -t ${{ env.DOCKER_IMAGE }}:latest

    - name: Push Docker image
      run: docker push ${{ env.DOCKER_IMAGE }}:latest

  deploy-to-ec2:
    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_SSH_USER }}
        key: ${{ env.PRIVATE_KEY }}
        script: |
          echo "🛑 Stopping existing container if running..."
          CONTAINER_ID=$(sudo docker ps -aq --filter "name=your-container-name")
          if [ -n "$CONTAINER_ID" ]; then
            sudo docker stop $CONTAINER_ID
            sudo docker rm $CONTAINER_ID
          fi

          echo "📦 Pulling new image..."
          sudo docker pull ${{ env.DOCKER_IMAGE }}:latest

          echo "🚀 Running new container..."
          sudo docker run -d \
            --name ${{ env.CONTAINER_NAME }} \
            -p ${{ env.HOST_PORT }}:${{ env.CONTAINER_PORT }} \
            -e TZ=${{ env.TIMEZONE }} \
            ${{ env.DOCKER_IMAGE }}:latest
